### ISSUE TITLE
词库修改: 修改 家衍人给

### ISSUE THREAD

**Issue by WRtux** [ouuan/Anti-YiGeDingLia#2]
词语（汉字）：##家衍人给##

拼音（以 QQ 为准）：jiāyǎnrénjǐ

我已试验过，该词语可以用来发红包，也可以用来接红包。

**Comment by WRtux** [comment]
QQ已修正“家衍人给”读音的错误。
目前只有“救过不给”还可以使用。

**Comment by ouuan** [comment]
THX, fixed!
