### ISSUE TITLE
BUG: 拼音ou的最近循环不循环

### ISSUE THREAD

**Issue by weathon** [ouuan/Anti-YiGeDingLia#3]
Bug 描述：拼音ou的最近循环不循环

Bug 复现方式（进行了什么操作、输入了什么）：输入ou，循环不是循环的

**Comment by ouuan** [comment]
我这里是“鸥鹭忘机 → 计穷智极”，您得到的输出是什么？

**Comment by weathon** [comment]
也是一样，但这个没有循环啊

**Comment by ouuan** [comment]
计穷智极是循环。

我要改成“最近自环”吗..

**Comment by ouuan** [comment]
而且这是“最近循环”，如果是整个是个循环的话，应该是“最短循环”。

**Comment by weathon** [comment]
OK，谢谢。是我理解错了
